CREATE TABLE senzori (
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
senzor VARCHAR(30) NOT NULL, 
lokacija VARCHAR(30) NOT NULL,
temperatura VARCHAR(10),
vlaznost VARCHAR(10) NOT NULL,
pritisak VARCHAR(10) NOT NULL,
vrijeme_ocitanja TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE  CURRENT_TIMESTAMP 
);